/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogGafasHomologadasEclipse2026RouteImport } from './routes/blog.gafas-homologadas-eclipse-2026'

const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogGafasHomologadasEclipse2026Route =
  BlogGafasHomologadasEclipse2026RouteImport.update({
    id: '/blog/gafas-homologadas-eclipse-2026',
    path: '/blog/gafas-homologadas-eclipse-2026',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/blog/gafas-homologadas-eclipse-2026': typeof BlogGafasHomologadasEclipse2026Route
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/blog/gafas-homologadas-eclipse-2026': typeof BlogGafasHomologadasEclipse2026Route
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/privacidad': typeof PrivacidadRoute
  '/blog/gafas-homologadas-eclipse-2026': typeof BlogGafasHomologadasEclipse2026Route
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/blog/gafas-homologadas-eclipse-2026'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/blog/gafas-homologadas-eclipse-2026'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/privacidad'
    | '/blog/gafas-homologadas-eclipse-2026'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  BlogGafasHomologadasEclipse2026Route: typeof BlogGafasHomologadasEclipse2026Route
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/gafas-homologadas-eclipse-2026': {
      id: '/blog/gafas-homologadas-eclipse-2026'
      path: '/blog/gafas-homologadas-eclipse-2026'
      fullPath: '/blog/gafas-homologadas-eclipse-2026'
      preLoaderRoute: typeof BlogGafasHomologadasEclipse2026RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  PrivacidadRoute: PrivacidadRoute,
  BlogGafasHomologadasEclipse2026Route: BlogGafasHomologadasEclipse2026Route,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
